
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Stratis.Bitcoin.IntegrationTests.Miners.ProofOfStakeMintCoinsSpecification.a_proof_of_stake_node_with_wallet")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Stratis.Bitcoin.IntegrationTests.Miners.ProofOfStakeMintCoinsSpecification.a_proof_of_work_node_with_wallet")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Stratis.Bitcoin.IntegrationTests.Miners.ProofOfStakeMintCoinsSpecification.create_tx_to_send_million_coins_from_pow_wallet_to_pos_node_wallet")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Stratis.Bitcoin.IntegrationTests.Miners.ProofOfStakeMintCoinsSpecification.it_mines_genesis_and_premine_blocks")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Stratis.Bitcoin.IntegrationTests.Miners.ProofOfStakeMintCoinsSpecification.it_syncs_with_proof_work_node")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Stratis.Bitcoin.IntegrationTests.Miners.ProofOfStakeMintCoinsSpecification.mine_coins_to_maturity")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Stratis.Bitcoin.IntegrationTests.Miners.ProofOfStakeMintCoinsSpecification.pos_node_mines_a_further_ten_blocks")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Stratis.Bitcoin.IntegrationTests.Miners.ProofOfStakeMintCoinsSpecification.pos_node_starts_staking")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Stratis.Bitcoin.IntegrationTests.Miners.ProofOfStakeMintCoinsSpecification.pos_node_wallet_has_earned_coins_through_staking")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Stratis.Bitcoin.IntegrationTests.Miners.ProofOfStakeMintCoinsSpecification.pow_wallet_broadcasts_tx_of_million_coins_and_pos_wallet_receives")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Stratis.Bitcoin.IntegrationTests.SmartContracts.SmartContractMinerTests.SmartContract_ReferencingInputInSameBlock~System.Threading.Tasks.Task")]