# City Chain - Continuous Integration Setup for Azure DevOps

parameters:
  name: ''
  queue: ''
  platform: ''
  reason: '$(Build.Reason)'
  arch: 'x64' # Only overriden by 32-bit Windows
  configuration: 'Release' # Only do debug if specified

phases:
- phase: ${{ parameters.name }}
  displayName: ${{ format('City Chain ({0}-{1})', parameters.platform, parameters.arch) }}
  queue: ${{ parameters.queue }}
  steps:

  - powershell: |
      $version = (Get-Content package.json) -join "`n" | ConvertFrom-Json | Select -ExpandProperty "version"
      Write-Host "##vso[task.setvariable variable=Build.BuildNumber]$version"
      Write-Host "##vso[task.setvariable variable=App.BuildNumber]$version" 
      Write-Host "BUILD_REASON: $Env:BUILD_REASON"
      Write-Host "BUILD_SOURCEBRANCH: $Env:BUILD_SOURCEBRANCH"
      Write-Host "BUILD_SOURCEBRANCHNAME: $Env:BUILD_SOURCEBRANCHNAME"
      Write-Host "SYSTEM_PULLREQUEST_PULLREQUESTID: $Env:SYSTEM_PULLREQUEST_PULLREQUESTID"
      Write-Host "SYSTEM_PULLREQUEST_PULLREQUESTNUMBER: $Env:SYSTEM_PULLREQUEST_PULLREQUESTNUMBER"
      Write-Host "SYSTEM_PULLREQUEST_SOURCEBRANCH: $Env:SYSTEM_PULLREQUEST_SOURCEBRANCH"
    displayName: version number

  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: publish
      projects: '**/City.Chain.csproj'
      workingDirectory: 'src/City.Chain'
      publishWebProjects: false
      zipAfterPublish: false
      modifyOutputPath: false
      arguments: ${{ format('-c {0} -r {1}-{2} -v m', parameters.configuration, parameters.platform, parameters.arch) }}

  # Run all unit tests, by applying the "*.Tests.csproj" filter it should avoid IntegrationTests projects.
  # Only run tests on Linux.
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    #condition: and(succeeded(), eq(variables['parameters.platform'], 'linux')) # Unable to get condition to work.
    inputs:
      command: test
      ${{ if eq(parameters.reason, 'Schedule') }}:
        projects: '**/*.Tests.csproj'
      ${{ if ne(parameters.reason, 'Schedule') }}:
        projects: '**/City.*.Tests.csproj'
      arguments: ${{ format('-c {0} -v m', parameters.configuration) }}

  - powershell: |
      $configuration="Release"
      $runtime=$env:runtime
      $git_commit=(git log --format=%h --abbrev=7 -n 1)
      $publish_directory="$env:workdir/src/City.Chain/bin/$configuration/netcoreapp2.1/$runtime/publish"
      $wrapped_directory="$env:workdir/src/City.Chain/bin/$configuration/netcoreapp2.1/$runtime/wrapped"
      $download_directory=$env:temp
      $warp="$download_directory/$env:warpfile"
      $project_path="$env:workdir/src/City.Chain/City.Chain.csproj"

      # Create the output folder for packaged output.
      New-Item -ItemType directory -Path $wrapped_directory
      # Not compatible with Mac.
      # md -Path $wrapped_directory

      Write-Host "Download directory is $download_directory" -foregroundcolor "Magenta"
      Write-Host "Current directory is $PWD" -foregroundcolor "Magenta"
      Write-Host "Git commit to build: $git_commit" -foregroundcolor "Magenta"

      Write-Host "Downloading warp..." -foregroundcolor "Magenta"
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      Invoke-WebRequest https://github.com/stratisproject/warp/releases/download/v0.2.1/$env:warpfile -O $warp

      If(Get-ChildItem $warp)
      {
          Write-Host "Warp downloaded succesfully." -foregroundcolor "Magenta"

          $size=((Get-Item "$warp").Length)
          Write-Host "Size is $size" -foregroundcolor "Magenta"
      }

      dotnet --info

      Write-Host "List of files to package:" -foregroundcolor "Magenta"
      Get-ChildItem -Path $publish_directory

      Write-Host "Packaging the daemon..." -foregroundcolor "Magenta"
      Write-Host "WARP:" $warp
      Write-Host "WARP-CMD:" $env:warpcmd
      Write-Host "--arch $env:arch --input_dir $publish_directory --exec $env:filename --output $wrapped_directory/$env:filename"

      If (-Not $env:warpcmd) {
        & $warp --arch $env:arch --input_dir $publish_directory --exec $env:filename --output $wrapped_directory/$env:filename
      }
      Else {
        & chmod +x "$env:warpcmd"
        & $env:warpcmd --arch $env:arch --input_dir $publish_directory --exec $env:filename --output $wrapped_directory/$env:filename
      }

      Write-Host "Done." -foregroundcolor "green"
    env:
      workdir: $(build.SourcesDirectory)

      ${{ if eq(parameters.platform, 'win') }}:
         runtime: 'win-x64'
         arch: 'windows-x64'
         warpfile: 'windows-x64.warp-packer.exe'
         filename: 'City.Chain.exe'
      ${{ if eq(parameters.platform, 'linux') }}:
         runtime: 'linux-x64'
         temp: '/tmp'
         arch: 'linux-x64'
         warpfile: 'linux-x64.warp-packer'
         warpcmd: '/tmp/linux-x64.warp-packer'
         filename: 'City.Chain'
      ${{ if eq(parameters.platform, 'osx') }}:
         runtime: 'osx-x64'
         temp: '/tmp'
         arch: 'macos-x64'
         warpfile: 'macos-x64.warp-packer'
         warpcmd: '/tmp/macos-x64.warp-packer'
         filename: 'City.Chain'
    displayName: package
    workingDirectory: $(build.SourcesDirectory)

  - task: ArchiveFiles@2
    displayName: archive
    inputs:
      rootFolderOrFile: ${{ format('src/City.Chain/bin/{0}/netcoreapp2.1/{1}-{2}/wrapped/', parameters.configuration, parameters.platform, parameters.arch) }}
      includeRootFolder: false

      ${{ if eq(parameters.platform, 'linux') }}:
        archiveFile: ${{ format('$(Build.ArtifactStagingDirectory)/City.Chain-$(App.BuildNumber)-{0}-{1}.tar.gz', parameters.platform, parameters.arch) }}
        archiveType: tar
      ${{ if ne(parameters.platform, 'linux') }}:
        archiveFile: ${{ format('$(Build.ArtifactStagingDirectory)/City.Chain-$(App.BuildNumber)-{0}-{1}.zip', parameters.platform, parameters.arch) }}  

  - task: marcelo-formentao.github-tools.github-release-publish-task.GitHubReleasePublish@0
    displayName: github release
    condition: and(succeeded(), eq(variables['build.sourcebranch'], 'refs/heads/master'))
    inputs:
      githubEndpoint: github
      githubRepository: 'CityChainFoundation/city-chain'
      githubReleaseTitle: 'City Chain (Release $(Build.BuildNumber))'
      githubReleasePrerelease: true
      githubReleaseAsset: '$(Build.ArtifactStagingDirectory)/City.Chain*.*'
      manifestJson: package.json
      githubEditRelease: true
