using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Stratis.SmartContracts.Standards;

namespace Stratis.SmartContracts.CLR.Compilation
{
    /// <summary>
    /// Resolves the assemblies allowed to be used in a Smart Contract
    /// </summary>
    public static class ReferencedAssemblyResolver
    {
        private static readonly List<string> AssemblyNames = new List<string>
        {
//            "api-ms-win-core-console-l1-1-0",
//"api-ms-win-core-datetime-l1-1-0",
//"api-ms-win-core-debug-l1-1-0",
//"api-ms-win-core-errorhandling-l1-1-0",
//"api-ms-win-core-file-l1-1-0",
//"api-ms-win-core-file-l1-2-0",
//"api-ms-win-core-file-l2-1-0",
//"api-ms-win-core-handle-l1-1-0",
//"api-ms-win-core-heap-l1-1-0",
//"api-ms-win-core-interlocked-l1-1-0",
//"api-ms-win-core-libraryloader-l1-1-0",
//"api-ms-win-core-localization-l1-2-0",
//"api-ms-win-core-memory-l1-1-0",
//"api-ms-win-core-namedpipe-l1-1-0",
//"api-ms-win-core-processenvironment-l1-1-0",
//"api-ms-win-core-processthreads-l1-1-0",
//"api-ms-win-core-processthreads-l1-1-1",
//"api-ms-win-core-profile-l1-1-0",
//"api-ms-win-core-rtlsupport-l1-1-0",
//"api-ms-win-core-string-l1-1-0",
//"api-ms-win-core-synch-l1-1-0",
//"api-ms-win-core-synch-l1-2-0",
//"api-ms-win-core-sysinfo-l1-1-0",
//"api-ms-win-core-timezone-l1-1-0",
//"api-ms-win-core-util-l1-1-0",
//"api-ms-win-crt-conio-l1-1-0",
//"api-ms-win-crt-convert-l1-1-0",
//"api-ms-win-crt-environment-l1-1-0",
//"api-ms-win-crt-filesystem-l1-1-0",
//"api-ms-win-crt-heap-l1-1-0",
//"api-ms-win-crt-locale-l1-1-0",
//"api-ms-win-crt-math-l1-1-0",
//"api-ms-win-crt-multibyte-l1-1-0",
//"api-ms-win-crt-private-l1-1-0",
//"api-ms-win-crt-process-l1-1-0",
//"api-ms-win-crt-runtime-l1-1-0",
//"api-ms-win-crt-stdio-l1-1-0",
//"api-ms-win-crt-string-l1-1-0",
//"api-ms-win-crt-time-l1-1-0",
//"api-ms-win-crt-utility-l1-1-0",
//"clrcompression",
//"clretwrc",
//"clrjit",
//"coreclr",
//"dbgshim",
//"hostpolicy",
"Microsoft.CSharp",
//"Microsoft.DiaSymReader.Native.amd64",
"Microsoft.VisualBasic",
"Microsoft.Win32.Primitives",
"Microsoft.Win32.Registry",
//"mscordaccore",
//"mscordaccore_amd64_amd64_4.6.28008.01",
//"mscordbi",
//"mscorlib",
//"mscorrc.debug",
//"mscorrc",
//"netstandard",
//"sos",
//"SOS.NETCore",
//"sos_amd64_amd64_4.6.28008.01",
"System.AppContext",
"System.Buffers",
"System.Collections.Concurrent",
"System.Collections",
"System.Collections.Immutable",
"System.Collections.NonGeneric",
"System.Collections.Specialized",
"System.ComponentModel.Annotations",
"System.ComponentModel.DataAnnotations",
"System.ComponentModel",
"System.ComponentModel.EventBasedAsync",
"System.ComponentModel.Primitives",
"System.ComponentModel.TypeConverter",
"System.Configuration",
"System.Console",
"System.Core",
"System.Data.Common",
"System.Data",
"System.Diagnostics.Contracts",
"System.Diagnostics.Debug",
"System.Diagnostics.DiagnosticSource",
"System.Diagnostics.FileVersionInfo",
"System.Diagnostics.Process",
"System.Diagnostics.StackTrace",
"System.Diagnostics.TextWriterTraceListener",
"System.Diagnostics.Tools",
"System.Diagnostics.TraceSource",
"System.Diagnostics.Tracing",
"System",
"System.Drawing",
"System.Drawing.Primitives",
"System.Dynamic.Runtime",
"System.Globalization.Calendars",
"System.Globalization",
"System.Globalization.Extensions",
"System.IO.Compression.Brotli",
"System.IO.Compression",
"System.IO.Compression.FileSystem",
"System.IO.Compression.ZipFile",
"System.IO",
"System.IO.FileSystem.AccessControl",
"System.IO.FileSystem",
"System.IO.FileSystem.DriveInfo",
"System.IO.FileSystem.Primitives",
"System.IO.FileSystem.Watcher",
"System.IO.IsolatedStorage",
"System.IO.MemoryMappedFiles",
"System.IO.Pipes.AccessControl",
"System.IO.Pipes",
"System.IO.UnmanagedMemoryStream",
"System.Linq",
"System.Linq.Expressions",
"System.Linq.Parallel",
"System.Linq.Queryable",
"System.Memory",
"System.Net",
"System.Net.Http",
"System.Net.HttpListener",
"System.Net.Mail",
"System.Net.NameResolution",
"System.Net.NetworkInformation",
"System.Net.Ping",
"System.Net.Primitives",
"System.Net.Requests",
"System.Net.Security",
"System.Net.ServicePoint",
"System.Net.Sockets",
"System.Net.WebClient",
"System.Net.WebHeaderCollection",
"System.Net.WebProxy",
"System.Net.WebSockets.Client",
"System.Net.WebSockets",
"System.Numerics",
"System.Numerics.Vectors",
"System.ObjectModel",
"System.Private.CoreLib",
"System.Private.DataContractSerialization",
"System.Private.Uri",
"System.Private.Xml",
"System.Private.Xml.Linq",
"System.Reflection.DispatchProxy",
"System.Reflection",
"System.Reflection.Emit",
"System.Reflection.Emit.ILGeneration",
"System.Reflection.Emit.Lightweight",
"System.Reflection.Extensions",
"System.Reflection.Metadata",
"System.Reflection.Primitives",
"System.Reflection.TypeExtensions",
"System.Resources.Reader",
"System.Resources.ResourceManager",
"System.Resources.Writer",
"System.Runtime.CompilerServices.VisualC",
"System.Runtime",
"System.Runtime.Extensions",
"System.Runtime.Handles",
"System.Runtime.InteropServices",
"System.Runtime.InteropServices.RuntimeInformation",
"System.Runtime.InteropServices.WindowsRuntime",
"System.Runtime.Loader",
"System.Runtime.Numerics",
"System.Runtime.Serialization",
"System.Runtime.Serialization.Formatters",
"System.Runtime.Serialization.Json",
"System.Runtime.Serialization.Primitives",
"System.Runtime.Serialization.Xml",
"System.Security.AccessControl",
"System.Security.Claims",
"System.Security.Cryptography.Algorithms",
"System.Security.Cryptography.Cng",
"System.Security.Cryptography.Csp",
"System.Security.Cryptography.Encoding",
"System.Security.Cryptography.OpenSsl",
"System.Security.Cryptography.Primitives",
"System.Security.Cryptography.X509Certificates",
"System.Security",
"System.Security.Principal",
"System.Security.Principal.Windows",
"System.Security.SecureString",
"System.ServiceModel.Web",
"System.ServiceProcess",
"System.Text.Encoding",
"System.Text.Encoding.Extensions",
"System.Text.RegularExpressions",
"System.Threading",
"System.Threading.Overlapped",
"System.Threading.Tasks.Dataflow",
"System.Threading.Tasks",
"System.Threading.Tasks.Extensions",
"System.Threading.Tasks.Parallel",
"System.Threading.Thread",
"System.Threading.ThreadPool",
"System.Threading.Timer",
"System.Transactions",
"System.Transactions.Local",
"System.ValueTuple",
"System.Web",
"System.Web.HttpUtility",
"System.Windows",
"System.Xml",
"System.Xml.Linq",
"System.Xml.ReaderWriter",
"System.Xml.Serialization",
"System.Xml.XDocument",
"System.Xml.XmlDocument",
"System.Xml.XmlSerializer",
"System.Xml.XPath",
"System.Xml.XPath.XDocument",
//"ucrtbase",
//"WindowsBase",
        };

        // System.Runtime forwards to mscorlib, so we can only get its Assembly by name
        // ref. https://github.com/dotnet/corefx/issues/11601
        private static readonly Assembly Runtime = Assembly.Load("System.Runtime");
        private static readonly Assembly Core = typeof(object).Assembly;

        /// <summary>
        /// The set of Assemblies that a <see cref="SmartContract"/> is required to reference
        /// </summary>
        public static HashSet<Assembly> AllowedAssemblies = new HashSet<Assembly>(AssemblyNames.Select(Assembly.Load)) {
                Runtime, 
                Core, 
                typeof(SmartContract).Assembly, 
                typeof(Enumerable).Assembly,
                typeof(IStandardToken).Assembly
            };


    }
}